### ISSUE TITLE
Enable tapping on the select/write/erase/... buttons with stylus pens

### ISSUE THREAD

**Issue by RyotaUshio** [daledesilva/obsidian_ink#17]
Thank you a lot for this wonderful project.

I have a suggestion. Currently, this plugin works as below:

- the handwriting section reacts only to stylus inputs
- the select/write/erase/undo/lock buttons react only to finger inputs

It would be great if it behaves as below instead:

- the handwriting section reacts only to stylus inputs (same as above)
- the select/write/erase/undo/lock buttons react to both finger **& stylus** inputs

This change will eliminate the need for switching between my pen and finger when I want to use the eraser tool.

**Comment by daledesilva** [comment]
I agree with your description of how it should work, however, on my iPad, that's exactly what it does.
(Apart from also allowing finger writing input if you haven't yet used the stylus).

Please let me know your device and operating system, and also type of stylus (Not all styluses are the same).

**Comment by RyotaUshio** [comment]
Thank you for the reply. My device is iPad Pro 12.9-inch 4th generation with iPadOS 16.6.1. I use Apple Pencil 2nd generation.

**Comment by daledesilva** [comment]
Thanks. THat's very clear now. I'll see if I can reproduce and fix it.

**Comment by daledesilva** [comment]
This is now fixed and will be in the new version once live. Thanks for reporting 😊

It's been fixed in 2 ways.

1. Because the embeds now show the buttons outside of the embed most of the time, it was mostly not an issue, however, scrolling the page down would cause the buttons to move over the embed and also opening the ink file directly should show the buttons over the embed.

2. The pointerUp still seemed to sometimes not activate the button on pen slip, and it added a new issue where you could slip onto an adjacent button and activate that on up accidently instead. The button's have therefore been changes to onPointDown (Pointer applies to both mouse and touch).

**Comment by daledesilva** [comment]
You can use this in v0.1.192 now if installing through BRAT.

**Comment by RyotaUshio** [comment]
Thank you so much for your effort. Unfortunately, this problem is still persisting:

https://github.com/daledesilva/obsidian_ink/assets/72342591/6b08de5f-5287-492b-a33f-ee75d69b8af1

(Obsidian 1.5.12 on iPad, Ink 0.1.192)

**Comment by daledesilva** [comment]
Thanks for the video. This looks more like issue #35 to me. Do you have the scribble setting activated on your iPad?
